"""add governed decision and workflow persistence"""

import sqlalchemy as sa

from alembic import op

revision = "410e2781b143"
down_revision = "e32819e0cf3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smart_trade_decision_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column(
            "examination_run_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "risk_run_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("ruleset_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("recommended_decision", sa.String(length=16), nullable=True),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("input_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("summary_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["examination_run_pk"],
            ["smart_trade_examination_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_run_pk"],
            ["smart_trade_risk_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_pk", "request_id"),
        sa.UniqueConstraint("case_pk", "run_number"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_decision_runs_case_pk"),
        "smart_trade_decision_runs",
        ["case_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_decision_runs_examination_run_pk"),
        "smart_trade_decision_runs",
        ["examination_run_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_decision_runs_risk_run_pk"),
        "smart_trade_decision_runs",
        ["risk_run_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_governed_workflows",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "decision_run_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("final_outcome", sa.String(length=16), nullable=True),
        sa.Column("maker_actor_id", sa.String(length=64), nullable=True),
        sa.Column("checker_actor_id", sa.String(length=64), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("finalized_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_pk"],
            ["smart_trade_decision_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_run_pk"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_governed_workflows_case_pk"),
        "smart_trade_governed_workflows",
        ["case_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_governed_workflows_decision_run_pk"),
        "smart_trade_governed_workflows",
        ["decision_run_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_workflow_tasks",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "decision_run_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("task_key", sa.String(length=100), nullable=False),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("assigned_role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reason_ids_json", sa.JSON(), nullable=False),
        sa.Column("assigned_actor_id", sa.String(length=64), nullable=True),
        sa.Column("resolution", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_pk"],
            ["smart_trade_decision_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_run_pk", "task_key"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_workflow_tasks_assigned_role"),
        "smart_trade_workflow_tasks",
        ["assigned_role"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_workflow_tasks_case_pk"),
        "smart_trade_workflow_tasks",
        ["case_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_workflow_tasks_decision_run_pk"),
        "smart_trade_workflow_tasks",
        ["decision_run_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_workflow_tasks_task_type"),
        "smart_trade_workflow_tasks",
        ["task_type"],
        unique=False,
    )
    op.create_table(
        "smart_trade_workflow_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "decision_run_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("task_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_pk"],
            ["smart_trade_decision_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_pk"],
            ["smart_trade_workflow_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_run_pk", "request_id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_workflow_events_case_pk"),
        "smart_trade_workflow_events",
        ["case_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_workflow_events_decision_run_pk"),
        "smart_trade_workflow_events",
        ["decision_run_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_workflow_events_event_type"),
        "smart_trade_workflow_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_workflow_events_task_pk"),
        "smart_trade_workflow_events",
        ["task_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_decision_overrides",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "decision_run_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "workflow_event_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("from_decision", sa.String(length=16), nullable=False),
        sa.Column("to_decision", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("reason_ids_json", sa.JSON(), nullable=False),
        sa.Column("evidence_reference", sa.String(length=255), nullable=True),
        sa.Column("previous_outcome", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_pk"],
            ["smart_trade_decision_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_event_pk"],
            ["smart_trade_workflow_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_event_pk"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_decision_overrides_case_pk"),
        "smart_trade_decision_overrides",
        ["case_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_decision_overrides_decision_run_pk"),
        "smart_trade_decision_overrides",
        ["decision_run_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_decision_overrides_workflow_event_pk"),
        "smart_trade_decision_overrides",
        ["workflow_event_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_decision_reasons",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "decision_run_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("reason_key", sa.String(length=120), nullable=False),
        sa.Column("reason_type", sa.String(length=40), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("impact", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("source_status", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("route_to", sa.String(length=32), nullable=True),
        sa.Column(
            "documentary_finding_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "risk_finding_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "examination_execution_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "provider_check_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_run_pk"],
            ["smart_trade_decision_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["documentary_finding_pk"],
            ["smart_trade_detected_discrepancies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["examination_execution_pk"],
            ["smart_trade_rule_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_check_pk"],
            ["smart_trade_provider_checks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_finding_pk"],
            ["smart_trade_detected_risk_findings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_run_pk", "reason_key"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_decision_reasons_decision_run_pk"),
        "smart_trade_decision_reasons",
        ["decision_run_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_decision_reasons_documentary_finding_pk"),
        "smart_trade_decision_reasons",
        ["documentary_finding_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_decision_reasons_examination_execution_pk"),
        "smart_trade_decision_reasons",
        ["examination_execution_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_decision_reasons_provider_check_pk"),
        "smart_trade_decision_reasons",
        ["provider_check_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_decision_reasons_reason_code"),
        "smart_trade_decision_reasons",
        ["reason_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_decision_reasons_risk_finding_pk"),
        "smart_trade_decision_reasons",
        ["risk_finding_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_finding_resolutions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "decision_run_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "decision_reason_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("task_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "workflow_event_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("resolution", sa.String(length=32), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_reason_pk"],
            ["smart_trade_decision_reasons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_run_pk"],
            ["smart_trade_decision_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_pk"],
            ["smart_trade_workflow_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_event_pk"],
            ["smart_trade_workflow_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_event_pk", "decision_reason_pk"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_finding_resolutions_decision_reason_pk"),
        "smart_trade_finding_resolutions",
        ["decision_reason_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_finding_resolutions_decision_run_pk"),
        "smart_trade_finding_resolutions",
        ["decision_run_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_finding_resolutions_task_pk"),
        "smart_trade_finding_resolutions",
        ["task_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_finding_resolutions_workflow_event_pk"),
        "smart_trade_finding_resolutions",
        ["workflow_event_pk"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_smart_trade_finding_resolutions_workflow_event_pk"),
        table_name="smart_trade_finding_resolutions",
    )
    op.drop_index(
        op.f("ix_smart_trade_finding_resolutions_task_pk"),
        table_name="smart_trade_finding_resolutions",
    )
    op.drop_index(
        op.f("ix_smart_trade_finding_resolutions_decision_run_pk"),
        table_name="smart_trade_finding_resolutions",
    )
    op.drop_index(
        op.f("ix_smart_trade_finding_resolutions_decision_reason_pk"),
        table_name="smart_trade_finding_resolutions",
    )
    op.drop_table("smart_trade_finding_resolutions")
    op.drop_index(
        op.f("ix_smart_trade_decision_reasons_risk_finding_pk"),
        table_name="smart_trade_decision_reasons",
    )
    op.drop_index(
        op.f("ix_smart_trade_decision_reasons_reason_code"),
        table_name="smart_trade_decision_reasons",
    )
    op.drop_index(
        op.f("ix_smart_trade_decision_reasons_provider_check_pk"),
        table_name="smart_trade_decision_reasons",
    )
    op.drop_index(
        op.f("ix_smart_trade_decision_reasons_examination_execution_pk"),
        table_name="smart_trade_decision_reasons",
    )
    op.drop_index(
        op.f("ix_smart_trade_decision_reasons_documentary_finding_pk"),
        table_name="smart_trade_decision_reasons",
    )
    op.drop_index(
        op.f("ix_smart_trade_decision_reasons_decision_run_pk"),
        table_name="smart_trade_decision_reasons",
    )
    op.drop_table("smart_trade_decision_reasons")
    op.drop_index(
        op.f("ix_smart_trade_decision_overrides_workflow_event_pk"),
        table_name="smart_trade_decision_overrides",
    )
    op.drop_index(
        op.f("ix_smart_trade_decision_overrides_decision_run_pk"),
        table_name="smart_trade_decision_overrides",
    )
    op.drop_index(
        op.f("ix_smart_trade_decision_overrides_case_pk"),
        table_name="smart_trade_decision_overrides",
    )
    op.drop_table("smart_trade_decision_overrides")
    op.drop_index(
        op.f("ix_smart_trade_workflow_events_task_pk"), table_name="smart_trade_workflow_events"
    )
    op.drop_index(
        op.f("ix_smart_trade_workflow_events_event_type"), table_name="smart_trade_workflow_events"
    )
    op.drop_index(
        op.f("ix_smart_trade_workflow_events_decision_run_pk"),
        table_name="smart_trade_workflow_events",
    )
    op.drop_index(
        op.f("ix_smart_trade_workflow_events_case_pk"), table_name="smart_trade_workflow_events"
    )
    op.drop_table("smart_trade_workflow_events")
    op.drop_index(
        op.f("ix_smart_trade_workflow_tasks_task_type"), table_name="smart_trade_workflow_tasks"
    )
    op.drop_index(
        op.f("ix_smart_trade_workflow_tasks_decision_run_pk"),
        table_name="smart_trade_workflow_tasks",
    )
    op.drop_index(
        op.f("ix_smart_trade_workflow_tasks_case_pk"), table_name="smart_trade_workflow_tasks"
    )
    op.drop_index(
        op.f("ix_smart_trade_workflow_tasks_assigned_role"), table_name="smart_trade_workflow_tasks"
    )
    op.drop_table("smart_trade_workflow_tasks")
    op.drop_index(
        op.f("ix_smart_trade_governed_workflows_decision_run_pk"),
        table_name="smart_trade_governed_workflows",
    )
    op.drop_index(
        op.f("ix_smart_trade_governed_workflows_case_pk"),
        table_name="smart_trade_governed_workflows",
    )
    op.drop_table("smart_trade_governed_workflows")
    op.drop_index(
        op.f("ix_smart_trade_decision_runs_risk_run_pk"), table_name="smart_trade_decision_runs"
    )
    op.drop_index(
        op.f("ix_smart_trade_decision_runs_examination_run_pk"),
        table_name="smart_trade_decision_runs",
    )
    op.drop_index(
        op.f("ix_smart_trade_decision_runs_case_pk"), table_name="smart_trade_decision_runs"
    )
    op.drop_table("smart_trade_decision_runs")
    # ### end Alembic commands ###
