"""add documentary examination and fact relations"""

import sqlalchemy as sa

from alembic import op

revision = "4c4c93c90831"
down_revision = "e52fad8ad293"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smart_trade_examination_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("playbook", sa.String(length=100), nullable=False),
        sa.Column("ruleset_version", sa.String(length=32), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("summary_json", sa.JSON(), nullable=False),
        sa.Column("input_snapshot_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_pk", "request_id"),
        sa.UniqueConstraint("case_pk", "run_number"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_examination_runs_case_pk"),
        "smart_trade_examination_runs",
        ["case_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_rule_executions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "examination_run_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("comparison_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "left_fact_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "right_fact_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("rule_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["examination_run_pk"],
            ["smart_trade_examination_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["left_fact_pk"],
            ["smart_trade_extracted_facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_fact_pk"],
            ["smart_trade_extracted_facts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("examination_run_pk", "rule_id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_rule_executions_examination_run_pk"),
        "smart_trade_rule_executions",
        ["examination_run_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_rule_executions_left_fact_pk"),
        "smart_trade_rule_executions",
        ["left_fact_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_rule_executions_right_fact_pk"),
        "smart_trade_rule_executions",
        ["right_fact_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_detected_discrepancies",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "examination_run_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "rule_execution_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("finding_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "expected_fact_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "observed_fact_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("expected_json", sa.JSON(), nullable=False),
        sa.Column("observed_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["examination_run_pk"],
            ["smart_trade_examination_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expected_fact_pk"],
            ["smart_trade_extracted_facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["observed_fact_pk"],
            ["smart_trade_extracted_facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_execution_pk"],
            ["smart_trade_rule_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_execution_pk"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_detected_discrepancies_case_pk"),
        "smart_trade_detected_discrepancies",
        ["case_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_detected_discrepancies_examination_run_pk"),
        "smart_trade_detected_discrepancies",
        ["examination_run_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_detected_discrepancies_expected_fact_pk"),
        "smart_trade_detected_discrepancies",
        ["expected_fact_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_detected_discrepancies_observed_fact_pk"),
        "smart_trade_detected_discrepancies",
        ["observed_fact_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_detected_discrepancies_rule_execution_pk"),
        "smart_trade_detected_discrepancies",
        ["rule_execution_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_fact_relations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "examination_run_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "rule_execution_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "source_fact_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "target_fact_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("relation_type", sa.String(length=32), nullable=False),
        sa.Column("comparison_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["examination_run_pk"],
            ["smart_trade_examination_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_execution_pk"],
            ["smart_trade_rule_executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_fact_pk"],
            ["smart_trade_extracted_facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_fact_pk"],
            ["smart_trade_extracted_facts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_execution_pk"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_fact_relations_case_pk"),
        "smart_trade_fact_relations",
        ["case_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_fact_relations_examination_run_pk"),
        "smart_trade_fact_relations",
        ["examination_run_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_fact_relations_rule_execution_pk"),
        "smart_trade_fact_relations",
        ["rule_execution_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_fact_relations_source_fact_pk"),
        "smart_trade_fact_relations",
        ["source_fact_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_fact_relations_target_fact_pk"),
        "smart_trade_fact_relations",
        ["target_fact_pk"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_smart_trade_fact_relations_target_fact_pk"),
        table_name="smart_trade_fact_relations",
    )
    op.drop_index(
        op.f("ix_smart_trade_fact_relations_source_fact_pk"),
        table_name="smart_trade_fact_relations",
    )
    op.drop_index(
        op.f("ix_smart_trade_fact_relations_rule_execution_pk"),
        table_name="smart_trade_fact_relations",
    )
    op.drop_index(
        op.f("ix_smart_trade_fact_relations_examination_run_pk"),
        table_name="smart_trade_fact_relations",
    )
    op.drop_index(
        op.f("ix_smart_trade_fact_relations_case_pk"), table_name="smart_trade_fact_relations"
    )
    op.drop_table("smart_trade_fact_relations")
    op.drop_index(
        op.f("ix_smart_trade_detected_discrepancies_rule_execution_pk"),
        table_name="smart_trade_detected_discrepancies",
    )
    op.drop_index(
        op.f("ix_smart_trade_detected_discrepancies_observed_fact_pk"),
        table_name="smart_trade_detected_discrepancies",
    )
    op.drop_index(
        op.f("ix_smart_trade_detected_discrepancies_expected_fact_pk"),
        table_name="smart_trade_detected_discrepancies",
    )
    op.drop_index(
        op.f("ix_smart_trade_detected_discrepancies_examination_run_pk"),
        table_name="smart_trade_detected_discrepancies",
    )
    op.drop_index(
        op.f("ix_smart_trade_detected_discrepancies_case_pk"),
        table_name="smart_trade_detected_discrepancies",
    )
    op.drop_table("smart_trade_detected_discrepancies")
    op.drop_index(
        op.f("ix_smart_trade_rule_executions_right_fact_pk"),
        table_name="smart_trade_rule_executions",
    )
    op.drop_index(
        op.f("ix_smart_trade_rule_executions_left_fact_pk"),
        table_name="smart_trade_rule_executions",
    )
    op.drop_index(
        op.f("ix_smart_trade_rule_executions_examination_run_pk"),
        table_name="smart_trade_rule_executions",
    )
    op.drop_table("smart_trade_rule_executions")
    op.drop_index(
        op.f("ix_smart_trade_examination_runs_case_pk"), table_name="smart_trade_examination_runs"
    )
    op.drop_table("smart_trade_examination_runs")
    # ### end Alembic commands ###
