"""add auditable risk orchestration persistence"""

import sqlalchemy as sa

from alembic import op

revision = "e32819e0cf3f"
down_revision = "4c4c93c90831"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smart_trade_risk_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("ruleset_version", sa.String(length=32), nullable=False),
        sa.Column("provider_set", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("input_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("summary_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_pk", "request_id"),
        sa.UniqueConstraint("case_pk", "run_number"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_risk_runs_case_pk"), "smart_trade_risk_runs", ["case_pk"], unique=False
    )
    op.create_table(
        "smart_trade_provider_checks",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "risk_run_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("check_key", sa.String(length=120), nullable=False),
        sa.Column("provider_type", sa.String(length=32), nullable=False),
        sa.Column("provider_name", sa.String(length=64), nullable=False),
        sa.Column("provider_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_run_pk"],
            ["smart_trade_risk_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("risk_run_pk", "check_key"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_provider_checks_case_pk"),
        "smart_trade_provider_checks",
        ["case_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_provider_checks_provider_type"),
        "smart_trade_provider_checks",
        ["provider_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_provider_checks_risk_run_pk"),
        "smart_trade_provider_checks",
        ["risk_run_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_risk_rule_executions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "risk_run_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "provider_check_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rule_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_check_pk"],
            ["smart_trade_provider_checks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_run_pk"],
            ["smart_trade_risk_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("risk_run_pk", "provider_check_pk", "rule_id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_risk_rule_executions_provider_check_pk"),
        "smart_trade_risk_rule_executions",
        ["provider_check_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_risk_rule_executions_risk_run_pk"),
        "smart_trade_risk_rule_executions",
        ["risk_run_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_detected_risk_findings",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "risk_run_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "provider_check_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "rule_execution_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("finding_type", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_value", sa.String(length=255), nullable=False),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_check_pk"],
            ["smart_trade_provider_checks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_run_pk"],
            ["smart_trade_risk_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_execution_pk"],
            ["smart_trade_risk_rule_executions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_execution_pk", "subject_value"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_detected_risk_findings_case_pk"),
        "smart_trade_detected_risk_findings",
        ["case_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_detected_risk_findings_category"),
        "smart_trade_detected_risk_findings",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_detected_risk_findings_provider_check_pk"),
        "smart_trade_detected_risk_findings",
        ["provider_check_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_detected_risk_findings_risk_run_pk"),
        "smart_trade_detected_risk_findings",
        ["risk_run_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_detected_risk_findings_rule_execution_pk"),
        "smart_trade_detected_risk_findings",
        ["rule_execution_pk"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_smart_trade_detected_risk_findings_rule_execution_pk"),
        table_name="smart_trade_detected_risk_findings",
    )
    op.drop_index(
        op.f("ix_smart_trade_detected_risk_findings_risk_run_pk"),
        table_name="smart_trade_detected_risk_findings",
    )
    op.drop_index(
        op.f("ix_smart_trade_detected_risk_findings_provider_check_pk"),
        table_name="smart_trade_detected_risk_findings",
    )
    op.drop_index(
        op.f("ix_smart_trade_detected_risk_findings_category"),
        table_name="smart_trade_detected_risk_findings",
    )
    op.drop_index(
        op.f("ix_smart_trade_detected_risk_findings_case_pk"),
        table_name="smart_trade_detected_risk_findings",
    )
    op.drop_table("smart_trade_detected_risk_findings")
    op.drop_index(
        op.f("ix_smart_trade_risk_rule_executions_risk_run_pk"),
        table_name="smart_trade_risk_rule_executions",
    )
    op.drop_index(
        op.f("ix_smart_trade_risk_rule_executions_provider_check_pk"),
        table_name="smart_trade_risk_rule_executions",
    )
    op.drop_table("smart_trade_risk_rule_executions")
    op.drop_index(
        op.f("ix_smart_trade_provider_checks_risk_run_pk"), table_name="smart_trade_provider_checks"
    )
    op.drop_index(
        op.f("ix_smart_trade_provider_checks_provider_type"),
        table_name="smart_trade_provider_checks",
    )
    op.drop_index(
        op.f("ix_smart_trade_provider_checks_case_pk"), table_name="smart_trade_provider_checks"
    )
    op.drop_table("smart_trade_provider_checks")
    op.drop_index(op.f("ix_smart_trade_risk_runs_case_pk"), table_name="smart_trade_risk_runs")
    op.drop_table("smart_trade_risk_runs")
    # ### end Alembic commands ###
