"""add versioned document intelligence storage"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

revision = "e52fad8ad293"
down_revision = "30af12917573"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smart_trade_document_versions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "document_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("case_pk", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column(
            "file_size_bytes", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_pk"],
            ["smart_trade_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_pk"],
            ["smart_trade_case_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_pk", "sha256"),
        sa.UniqueConstraint("document_pk", "version_number"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_document_versions_case_pk"),
        "smart_trade_document_versions",
        ["case_pk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_smart_trade_document_versions_document_pk"),
        "smart_trade_document_versions",
        ["document_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_document_pages",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "document_version_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column(
            "text_content", sa.Text().with_variant(mysql.LONGTEXT(), "mysql"), nullable=False
        ),
        sa.Column("text_length", sa.Integer(), nullable=False),
        sa.Column("extraction_method", sa.String(length=32), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_pk"],
            ["smart_trade_document_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_version_pk", "page_number"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_document_pages_document_version_pk"),
        "smart_trade_document_pages",
        ["document_version_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_document_processing_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "document_version_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("parser", sa.String(length=64), nullable=False),
        sa.Column("llm_model", sa.String(length=255), nullable=True),
        sa.Column("document_type", sa.String(length=64), nullable=True),
        sa.Column("classification_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_pk"],
            ["smart_trade_document_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_version_pk", "run_number"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_document_processing_runs_document_version_pk"),
        "smart_trade_document_processing_runs",
        ["document_version_pk"],
        unique=False,
    )
    op.create_table(
        "smart_trade_extracted_facts",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "processing_run_pk",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=True),
        sa.Column("normalized_json", sa.JSON(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("evidence_status", sa.String(length=32), nullable=False),
        sa.Column("review_reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["processing_run_pk"],
            ["smart_trade_document_processing_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("processing_run_pk", "field_name"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    op.create_index(
        op.f("ix_smart_trade_extracted_facts_processing_run_pk"),
        "smart_trade_extracted_facts",
        ["processing_run_pk"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_smart_trade_extracted_facts_processing_run_pk"),
        table_name="smart_trade_extracted_facts",
    )
    op.drop_table("smart_trade_extracted_facts")
    op.drop_index(
        op.f("ix_smart_trade_document_processing_runs_document_version_pk"),
        table_name="smart_trade_document_processing_runs",
    )
    op.drop_table("smart_trade_document_processing_runs")
    op.drop_index(
        op.f("ix_smart_trade_document_pages_document_version_pk"),
        table_name="smart_trade_document_pages",
    )
    op.drop_table("smart_trade_document_pages")
    op.drop_index(
        op.f("ix_smart_trade_document_versions_document_pk"),
        table_name="smart_trade_document_versions",
    )
    op.drop_index(
        op.f("ix_smart_trade_document_versions_case_pk"), table_name="smart_trade_document_versions"
    )
    op.drop_table("smart_trade_document_versions")
    # ### end Alembic commands ###
